services:
  ip-checker:
    build: .
    container_name: ip_checker_site
    restart: unless-stopped
    # Важные права для работы VPN внутри контейнера
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      # Замените на ваш Network ID из панели ZeroTier!
      - ZT_NETWORK_ID=8185934e6af6ceb3
    volumes:
      # Сохраняем идентификатор устройства (Node ID), чтобы он не менялся при перезапуске
      - zt_data:/var/lib/zerotier-one
    


volumes:
  zt_data:
