services:
  ip-checker:
    build: .
    container_name: ip_checker_site
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - ZT_NETWORK_ID=8185934e6af6ceb3
    volumes:
      - zt_data:/var/lib/zerotier-one

  zt-dns:
    image: coredns/coredns:1.11.3
    container_name: ip_checker_dns
    restart: unless-stopped
    network_mode: service:ip-checker
    volumes:
      - ./dns/Corefile:/Corefile:ro
    command: ["-conf", "/Corefile"]
    

    

volumes:
  zt_data:
